modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/liopyu/liosplayerAnimatorAPI/issues"
license = "MIT License"

[[mods]]
modId = "liosplayeranimatorapi"
version = "${version}"
displayName = "Lio's Player Animator API"
authors = "Zigy,Liopyu"
description = '''
Lio's fork of Zigy's API for playing player animations from server side.
'''

logoFile = "icon.png"

[[dependencies.liosplayeranimatorapi]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.liosplayeranimatorapi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.liosplayeranimatorapi]]
modId = "playeranimator"
mandatory = true
versionRange = "[${player_anim_version},)"
ordering = "AFTER"
side = "CLIENT"
[[dependencies.liosplayeranimatorapi]]
modId = "animationjs"
mandatory = false
versionRange = "[1.20.1-0.0.5,)"
ordering = "NONE"
side = "BOTH"