modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/ZigyTheBird/ZigysPlayerAnimatorAPI/issues"
license = "MIT License"

[[mixins]]
config = "playeranimatorapi-common.mixins.json"
[[mixins]]
config = "playeranimatorapi.mixins.json"

[[mods]]
modId = "playeranimatorapi"
version = "${version}"
displayName = "Zigy's Player Animator API"
authors = "Zigy"
description = '''
API for playing player animations from server side.
'''

logoFile = "icon.png"

[[dependencies.playeranimatorapi]]
modId = "neoforge"
type="required"
versionRange = "[20.4.225,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playeranimatorapi]]
modId = "minecraft"
type="required"
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playeranimatorapi]]
modId = "playeranimator"
type="required"
versionRange = "[${player_anim_version},)"
ordering = "AFTER"
side = "CLIENT"